<?php

namespace Database\Factories;

use App\Enums\AppointmentStatus;
use App\Enums\UserRole;
use App\Models\Patient;
use App\Models\Room;
use App\Models\Service;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Appointment>
 */
class AppointmentFactory extends Factory
{
    public function definition(): array
    {
        $scheduledDate = fake()->dateTimeBetween('-1 month', '+2 months');
        $serviceDuration = fake()->randomElement([15, 20, 30, 45, 60, 90]);

        $start = Carbon::instance($scheduledDate)->setTime(fake()->numberBetween(8, 15), fake()->randomElement([0, 15, 30, 45]), 0);
        $end = (clone $start)->addMinutes($serviceDuration);

        return [
            'code' => Str::random(10), // will be generated by model booted() when empty
            'patient_id' => Patient::factory(),
            'service_id' => Service::factory()->state(fn () => ['duration_minutes' => $serviceDuration]),
            'doctor_id' => User::factory()->state(fn () => ['role' => UserRole::DOCTOR]),
            'room_id' => fake()->boolean(85) ? Room::factory() : null,
            'scheduled_date' => $start->format('Y-m-d'),
            'scheduled_start' => $start->format('H:i:s'),
            'scheduled_end' => $end->format('H:i:s'),
            'status' => fake()->randomElement([
                AppointmentStatus::PENDING,
                AppointmentStatus::CONFIRMED,
                AppointmentStatus::ONGOING,
                AppointmentStatus::DONE,
                AppointmentStatus::CANCELLED,
            ]),
            'snap_token' => fake()->optional()->sha1(),
            'notes' => fake()->optional()->sentence(),
        ];
    }
}
