<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Room>
 */
class RoomFactory extends Factory
{
    public function definition(): array
    {
        return [
            'name' => 'Ruang ' . fake()->unique()->numberBetween(1, 50),
            'code' => null, // will be generated by model booted() when empty
            'notes' => fake()->optional()->sentence(),
        ];
    }
}
