<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Service>
 */
class ServiceFactory extends Factory
{
    public function definition(): array
    {

        $serviceNames = [
            'Konsultasi Dokter',
            'Pemeriksaan Fisik',
            'Tes Laboratorium',
            'Rontgen',
            'USG',
            'EKG',
            'Terapi Fisik',
            'Vaksinasi',
            'Pengobatan Luka',
            'Konseling Gizi',
        ];

        return [
            'name' => fake()->randomElement($serviceNames),
            'code' => null, // will be generated by model booted() when empty
            'duration_minutes' => fake()->randomElement([15, 20, 30, 45, 60, 90]),
            'description' => fake()->optional()->sentence(),
            'color' => fake()->optional()->safeHexColor(),
        ];
    }
}
